server:
  port: 8090
spring:
  application:
    name: dear-comrade-user-profile
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dear-comrade-discovery:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html

user-profile:
  user-name: shiva
  password: shiva

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: "true"
    ratelimiters:
      enabled: "true"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
