server:
  port: 8761

eureka:
  instance:
    hostname: dear_comared_discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: dear_comared_discovery
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
