server:
  port: 8761

eureka:
  instance:
    hostname: dear-comrade-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: dear-comrade-discovery
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
