server:
  port: 8761

eureka:
  #  instance:
  #    hostname: localhost
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: dear-comrade-discovery
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
