server:
  port: 8091
spring:
  application:
    name: dear_comared_tutorial
  cloud:
    config:
      uri: http://localhost:8888
eureka:
    instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
