server:
  port: 8090
spring:
  application:
    name: dear_comared_user_profile
  profiles:
    active:
      - dev
  cloud:
    config:
      uri: http://localhost:8888
#      enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


user-profile:
  user-name: shiva
  password: shiva