server:
  port: 9999
spring:
  application:
    name: dear-comrade-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        addToSimpleUrlHandlerMapping: true
        routes:
          - id: dear-comrade-tutorial
            uri: lb://dear-comrade-tutorial
            predicates:
              - Path=/tutorials/**
            filters:
              - AddRequestHeader=X-Welcome,Hi
              - AddResponseHeader=X-Welcome,bye
          - id: openapi
            uri: http://localhost:${server.port}
            predicates:
              - Path=/v3/api-docs/**
            filters:
              - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  main:
    web-application-type: reactive
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: tutorials
        url: /v3/api-docs/tutorials
