server:
  port: 8091
spring:
  application:
    name: dear_comared_tutorial
  cloud:
    config:
      uri: http://localhost:8888
  jackson:
    serialization:
      INDENT_OUTPUT: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

user-profile:
  base-url: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#RETRY
resilience4j.retry:
  instances:
    tutorial-api-retry:
      maxAttempts: 6
      enableExponentialBackoff: true
      waitDuration: 30s
    user-api-retry:
      maxAttempts: 2
      enableExponentialBackoff: true
      waitDuration: 5s
# CIRCUIT Breaker
resilience4j.circuitbreaker:
  instances:
    user-circuit-breaker:
      registerHealthIndicator: true
      slidingWindowSize: 60
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2000
      failureRateThreshold: 50
#      ignoreExceptions:
#        - com.jsession4d.feignclient.BusinessException

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: "true"
    ratelimiters:
      enabled: "true"
  endpoint:
    health:
      show-details: always
