server:
  port: 8091
spring:
  application:
    name: dear_comared_tutorial
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

user-profile:
  base-url: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j.retry:
  instances:
    tutorial-api-retry:
      maxAttempts: 6
      enableExponentialBackoff: true
      waitDuration: 1s
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
    ratelimiters:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
