server:
  port: 9999
spring:
  application:
    name: dear-comrade-cloud-gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      #      routes:
      #        - id: dear_comared_tutorial
      #          uri: http://localhost:8091
      #          predicates:
      #            - Path=/tutorials/**
      #          filters:
      #            - AddRequestHeader=X-Welcome,Hi
      #            - AddResponseHeader=X-Welcome,bye

  main:
    web-application-type: reactive

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dear-comrade-discovery:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

springdoc:
  swagger-ui:
    urls:
      - name: tutorials
        url: /v3/api-docs/tutorials
