server:
  port: 8091
spring:
  application:
    name: dear-comrade-tutorial
  jackson:
    serialization:
      INDENT_OUTPUT: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dear-comrade-discovery:8761/eureka/

user-profile:
  base-url: http://dear-comrade-user-profile:8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#RETRY
resilience4j.retry:
  instances:
    tutorial-api-retry:
      maxAttempts: 6
      enableExponentialBackoff: true
      waitDuration: 30s
    user-api-retry:
      maxAttempts: 2
      enableExponentialBackoff: true
      waitDuration: 5s
# CIRCUIT Breaker
resilience4j.circuitbreaker:
  instances:
    user-circuit-breaker:
      registerHealthIndicator: true
      slidingWindowSize: 60
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2000
      failureRateThreshold: 50
#      ignoreExceptions:
#        - com.jsession4d.feignclient.BusinessException

# Rate Limiter
resilience4j.ratelimiter:
  instances:
    user-rate-limiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

# Bulk Head
resilience4j.thread-pool-bulkhead:
  instances:
    user-bulk-head:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      writableStackTraceEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: "true"
    ratelimiters:
      enabled: "true"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
