server:
  port: 8090
spring:
  application:
    name: dear-comrade-user-profile
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dear-comrade-discovery:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html

user-profile:
  user-name: shiva
  password: shiva
