spring:
  application:
    name: elastic-query-service
server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-service:
  version: v1

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true

user-config:
  username: shiva
  password: "{cipher}AQChzXuuqOAEEGenJWcFI/LZ3sYhlIKkYzrDOMAYWdD1biKwpUpeH0xD02y1g9AO24jg8zU8OEyqLoCpV0w9OYjgMyxrV6aqUQGZUI6mW/rfmWBz8yT+6cZPHy6/Q1ekKpg3Nh0XVjowQiUiATkLj5ocygWfijp282MvTVcFc0uAIdNe7FoHqEMlJvihfUmwha6s61vEmT7BhcGcjSbnwBn2/B+hW495GTxSrMK+am9YiviC0WSa4c9/npmRiiB5jy5fbONclC8aDb6ocNLtQcfLrSnLNt0ZGL0d8QyzdyPZaqgFgTBKbUGwu6GNX5vnLjYjzpy+uHiQoNi1T8PN/SMgTSBoYxA8NMmcJaES99keMiqUHCSo4lKoYJS15jMtOVc="
  role: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /vendors/**,/resources/**,/api/role/**,/web/resume/**,/api/user/**,/swagger-ui/**,/v3/api-docs/swagger-config/**,/v3/api-docs/**,/api/auth/**,/api/resume/**,/swagger-ui.html/**./api-docs/**
