eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
token:
  expiration_time: "864000000"
  secret: hfgry463hf746hf573ydh475fhy5739
spring:
  application:
    name: studentpool-presentations
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:~/test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: "true"
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
login:
  url:
    path: /users/login
server:
  port: "8002"
