server:
  port: 8012
spring:
  application:
    name: studentpool_notes
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankAccount
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: create-drop
