spring:
  application:
    name: studentpool_preparation
  datasource:
    username: sa
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: "true"
server:
  port: 8011
eureka:
  client:
    fetchRegistry: "true"
    registerWithEureka: "true"
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
