eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: studentpool-money
server:
  port: '8004'
app:
  env: prod